const translations = {
  en: {
    authTitle: 'Anas Plus',
    login: 'Login',
    register: 'Register',
    loading: 'Loading...',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    passwordHint: 'Password must be at least 8 characters with uppercase, lowercase, and number',

    searchPlaceholder: 'Search gyms, locations...',
    quickMap: 'Map',
    quickBookings: 'Bookings',
    quickWorkouts: 'Workouts',
    activeCount: '{count} active',
    locationsTitle: 'Our Locations',
    resultsTitle: 'Results',
    nearbyTitle: 'Near You',
    featuredTitle: 'Featured',
    viewAll: 'View All',
    upcomingSessions: 'Upcoming Sessions',
    seeAll: 'See All',
    noLocations: 'No locations found',
    adjustSearch: 'Try adjusting your search',
    bookingsModal: 'My Bookings',
    upcoming: 'Upcoming',
    pastSessions: 'Past Sessions',
    noBookings: 'No bookings yet',
    startJourney: 'Start your fitness journey today',
    exploreLocations: 'Explore Locations',
    allLabel: 'All',
    errorTitle: 'Error',
    validationTitle: 'Validation',
    errorLoadProgrammes: 'Failed to load programmes',
    errorLoadWorkouts: 'Failed to load workouts',
    titleRequired: 'Title is required',
    userNotIdentified: 'User not identified. Please log in again.',
    errorCreateProgramme: 'Failed to create programme',
    durationWeeksShort: '{count} wks',
    durationNA: 'Duration N/A',
    noObjective: 'No objective',
    workoutsCount: '{count} workouts',
    active: 'Active',
    inactive: 'Inactive',
    workoutNumber: 'Workout #{num}',
    orderLabel: 'Order',
    weekDayLabel: 'Week day (1-7)',
    remove: 'Remove',
    myProgrammes: 'My Programmes',
    newLabel: 'New',
    searchProgrammes: 'Search programmes',
    newest: 'Newest',
    oldest: 'Oldest',
    programmesCount: '{count} programme(s)',
    reset: 'Reset',
    retry: 'Retry',
    noProgrammesFilters: 'No programmes match your filters',
    noProgrammes: 'No programmes yet',
    adjustSearchFilters: 'Try adjusting the search or filters',
    createProgrammeHint: 'Create one to organize your workouts',
    clearFilters: 'Clear filters',
    createProgramme: 'Create Programme',
    titleLabel: 'Title *',
    programmeTitlePlaceholder: 'Programme title',
    objectiveLabel: 'Objective',
    objectivePlaceholder: 'Fat loss, strength...',
    descriptionLabel: 'Description',
    programmeNotesPlaceholder: 'Notes about this programme',
    durationWeeksLabel: 'Duration (weeks)',
    durationPlaceholder: 'e.g. 8',
    workoutsInProgramme: 'Workouts in this programme',
    addWorkout: 'Add workout',
    addWorkoutsHelper: 'Add workouts to define the sequence for this programme.',
    cancel: 'Cancel',
    save: 'Save',
    accessTitle: 'Access',
    workoutFallback: 'Unable to load full workout details, showing basic info.',
    selectWorkoutPlease: 'Please select at least one workout',
    errorUpdateProgrammeWorkouts: 'Failed to update programme workouts',
    removeWorkoutTitle: 'Remove workout',
    removeWorkoutConfirm: 'Remove this workout from the programme?',
    errorRemoveWorkout: 'Failed to remove workout from programme',
    deleteProgramme: 'Delete programme',
    deleteProgrammeConfirm: 'This will remove the programme permanently. Continue?',
    delete: 'Delete',
    errorDeleteProgramme: 'Failed to delete programme',
    errorLoadProgramme: 'Failed to load programme',
    programmeNotFound: 'Programme not found',
    programmeLabel: 'Programme',
    noObjectiveProvided: 'No objective provided',
    addWorkoutsCTA: 'Add workouts',
    backToList: 'Back to list',
    workoutsByWeekDay: 'Workouts by week/day ({count})',
    noWorkoutsAttached: 'No workouts attached to this programme',
    weekLabel: 'Week {num}',
    noWorkout: 'No workout',
    unscheduled: 'Unscheduled',
    addWorkoutsTitle: 'Add workouts to programme',
    workoutPlaceholder: 'Workout {id}',
    weekOrderLabel: 'Week (order)',
    addAnother: 'Add another',
    dayMon: 'Mon',
    dayTue: 'Tue',
    dayWed: 'Wed',
    dayThu: 'Thu',
    dayFri: 'Fri',
    daySat: 'Sat',
    daySun: 'Sun',
    exercisesCount: '{count} exercises',
    exercisesNotLoaded: 'Exercises not loaded',
    myWorkoutsTitle: 'My Workouts',
    myWorkoutsSubtitle: 'Curated list of your sessions with quick stats',
    searchWorkouts: 'Search workouts...',
    workoutsCountFound: '{count} workout(s) found',
    programmesBtn: 'Programmes',
    noWorkoutsSearch: 'No workouts match your search',
    noWorkoutsFound: 'No workouts found',
    clearSearch: 'Clear Search',
    createWorkout: 'Create Workout',
    createAttachExercise: 'Create & Attach Exercise',
    workoutTitlePlaceholder: 'Title *',
    notesPlaceholder: 'Notes',
    durationMinutesPlaceholder: 'Duration (minutes)',
    waterPlaceholder: 'Water consumption (L)',
    newExerciseTitle: 'New Exercise',
    selectedWorkoutId: 'Selected Workout ID: {id}',
    none: 'None',
    exerciseNameLabel: 'Exercise Name *',
    exerciseNamePlaceholder: 'Enter exercise name',
    whereTraining: 'Where are you training?',
    atHome: 'At Home',
    locationHelper: 'Pick your branch to see its machines, or choose Home to load everything.',
    selectBranch: 'Select Branch (gym)',
    noBranches: 'No branches available',
    coachNameSelect: 'Coach Name (select)',
    noCoachesBranch: 'No coaches for this branch',
    selectBranchFirst: 'Select a branch first',
    coachNameManual: 'Coach Name (manual)',
    coachNamePlaceholder: 'Enter coach name or type your own',
    coachNameHelper: 'Selection is stored as plain text for traceability.',
    selectMachine: 'Select Machine',
    noMachinesLocation: 'No machines available for this location',
    selectLocationFirst: 'Select where you are training to load machines',
    selectMovement: 'Select Movement',
    selectCharge: 'Select Charge',
    setsLabel: 'Sets *',
    repsLabel: 'Reps *',
    setsPlaceholder: 'Sets',
    repsPlaceholder: 'Reps',
    instructionsLabel: 'Instructions (optional)',
    instructionsPlaceholder: 'Enter instructions',
    addExercise: 'Add Exercise',
    errorLoadWorkoutsList: 'Failed to load workouts. Please try again.',
    errorLoadBranches: 'Failed to load branches',
    errorLoadMachines: 'Failed to load machines',
    errorLoadCoaches: 'Failed to load coaches for this branch',
    errorLoadMovements: 'Failed to load movements',
    errorLoadCharges: 'Failed to load charges for selected machine',
    workoutTitleRequired: 'Workout title is required',
    successTitle: 'Success',
    errorCreateWorkout: 'Failed to create workout',
    selectWorkoutFirst: 'Please select a workout first',
    exerciseFieldsRequired: 'Name, sets and reps are required for the exercise',
    exerciseCreatedAttached: 'Exercise created and attached successfully',
    errorCreateAttachExercise: 'Unable to create or attach the exercise',
    noOptions: 'No options available',
    noNotes: 'No notes',
    dateNA: 'Date N/A',
    errorLoadWorkoutDetails: 'Failed to load workout details',
    errorUpdateExerciseData: 'Failed to update exercise data.',
    errorToggleStatus: 'Could not update exercise status. Please try again.',
    invalidInput: 'Invalid input',
    enterValidOrder: 'Please enter a valid number for order.',
    orderUpdated: 'Order updated!',
    errorUpdateOrder: 'Failed to update order. Please try again.',
    confirmDelete: 'Confirm Delete',
    confirmDeleteExercise: 'Remove this exercise from the workout and delete it permanently?',
    delete: 'Delete',
    exerciseRemoved: 'Exercise removed and deleted successfully.',
    errorDeleteExercise: 'Failed to remove and delete exercise. Please try again.',
    achNoteCompleted: 'Completed',
    achNoteNearly: 'Nearly complete',
    achNoteAlmost: 'Almost done',
    achNoteGetting: 'Getting there',
    achNoteStarted: 'Just started',
    achNoteNotStarted: 'Not started',
    setsReps: 'Sets x Reps',
    achievement: 'Achievement',
    achievementRange: 'Achievement must be between 0 and 100',
    completed: 'Completed',
    inProgress: 'In progress',
    movement: 'Movement',
    machine: 'Machine',
    charge: 'Charge',
    deleteExercise: 'Delete Exercise',
    workoutTitleLabel: 'Workout: {title}',
    duration: 'Duration',
    water: 'Water',
    type: 'Type',
    restDay: 'Rest day',
    workoutDay: 'Workout',
    done: 'Done',
    pending: 'Pending',
    noExercisesFound: 'No exercises found.',
    userDefault: 'User',
    errorLoadUserData: 'Failed to load user data',
    sessionExpired: 'Session Expired',
    pleaseLoginAgain: 'Please log in again',
    errorLoadProgress: 'Failed to load progress data',
    confirmDeleteProgress: 'Are you sure you want to delete this entry?',
    deletedTitle: 'Deleted',
    progressDeleted: 'Progress entry deleted successfully',
    errorDeleteProgress: 'Failed to delete progress',
    dateRequired: 'Date is required',
    oneMeasurement: 'Please provide at least one measurement',
    dateFormat: 'Please enter date in YYYY-MM-DD format',
    validWeight: 'Please enter a valid weight',
    validHeight: 'Please enter a valid height',
    bodyFatRange: 'Body fat percentage must be between 0 and 100',
    muscleMassRange: 'Muscle mass percentage must be between 0 and 100',
    progressAdded: 'Progress added successfully',
    errorSaveProgress: 'Failed to save progress',
    loadingProgress: 'Loading progress...',
    progressTracker: 'Progress Tracker',
    progressFor: "{name}'s progress",
    progressSubtitle: 'Track weight, muscle mass, and body fat',
    entriesCount: '{count} entries',
    noEntries: 'No entries',
    noRecentData: 'No recent data',
    height: 'Height',
    muscle: 'Muscle',
    recentTrends: 'Recent trends',
    addProgress: 'Add new progress',
    addProgressHint: 'Save your measurements to track your progress.',
    weightPlaceholder: 'Weight (kg) - optional',
    heightPlaceholder: 'Height (cm) - optional',
    bodyFatPlaceholder: 'Body Fat % - optional',
    musclePlaceholder: 'Muscle Mass % - optional',
    datePlaceholder: 'Recorded Date (YYYY-MM-DD) - required',
    today: 'Today',
    saveProgress: 'Save progress',
    history: 'History',
    noProgressYet: 'No progress data yet. Add your first entry above!',
  },
  fr: {
    authTitle: 'Anas Plus',
    login: 'Connexion',
    register: 'Inscription',
    loading: 'Chargement...',
    fullName: 'Nom complet',
    email: 'Email',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    passwordHint: '8+ caractères avec majuscule, minuscule et chiffre',

    searchPlaceholder: 'Recherchez des salles, lieux...',
    quickMap: 'Carte',
    quickBookings: 'Réservations',
    quickWorkouts: 'Entraînements',
    activeCount: '{count} actif(s)',
    locationsTitle: 'Nos emplacements',
    resultsTitle: 'Résultats',
    nearbyTitle: 'Près de vous',
    featuredTitle: 'À la une',
    viewAll: 'Voir tout',
    upcomingSessions: 'Séances à venir',
    seeAll: 'Voir tout',
    noLocations: 'Aucun emplacement trouvé',
    adjustSearch: 'Essayez d’ajuster votre recherche',
    bookingsModal: 'Mes réservations',
    upcoming: 'À venir',
    pastSessions: 'Séances passées',
    noBookings: 'Aucune réservation',
    startJourney: 'Commencez votre parcours fitness',
    exploreLocations: 'Explorer les salles',
    allLabel: 'Tout',
    errorTitle: 'Erreur',
    validationTitle: 'Validation',
    errorLoadProgrammes: 'Échec du chargement des programmes',
    errorLoadWorkouts: 'Échec du chargement des entraînements',
    titleRequired: 'Le titre est requis',
    userNotIdentified: 'Utilisateur non identifié. Veuillez vous reconnecter.',
    errorCreateProgramme: 'Échec de création du programme',
    durationWeeksShort: '{count} sem',
    durationNA: 'Durée N/D',
    noObjective: 'Aucun objectif',
    workoutsCount: '{count} séances',
    active: 'Actif',
    inactive: 'Inactif',
    workoutNumber: 'Entraînement #{num}',
    orderLabel: 'Ordre',
    weekDayLabel: 'Jour de la semaine (1-7)',
    remove: 'Supprimer',
    myProgrammes: 'Mes programmes',
    newLabel: 'Nouveau',
    searchProgrammes: 'Rechercher des programmes',
    newest: 'Plus récent',
    oldest: 'Plus ancien',
    programmesCount: '{count} programme(s)',
    reset: 'Réinitialiser',
    retry: 'Réessayer',
    noProgrammesFilters: 'Aucun programme ne correspond aux filtres',
    noProgrammes: 'Aucun programme pour l’instant',
    adjustSearchFilters: 'Ajustez la recherche ou les filtres',
    createProgrammeHint: 'Créez-en un pour organiser vos entraînements',
    clearFilters: 'Effacer les filtres',
    createProgramme: 'Créer un programme',
    titleLabel: 'Titre *',
    programmeTitlePlaceholder: 'Titre du programme',
    objectiveLabel: 'Objectif',
    objectivePlaceholder: 'Perte de poids, force...',
    descriptionLabel: 'Description',
    programmeNotesPlaceholder: 'Notes sur ce programme',
    durationWeeksLabel: 'Durée (semaines)',
    durationPlaceholder: 'ex. 8',
    workoutsInProgramme: 'Entraînements dans ce programme',
    addWorkout: 'Ajouter un entraînement',
    addWorkoutsHelper: 'Ajoutez des entraînements pour définir la séquence.',
    cancel: 'Annuler',
    save: 'Enregistrer',
    accessTitle: 'Accès',
    workoutFallback: 'Impossible de charger les détails complets, affichage des infos de base.',
    selectWorkoutPlease: 'Sélectionnez au moins un entraînement',
    errorUpdateProgrammeWorkouts: 'Échec de mise à jour des entraînements',
    removeWorkoutTitle: 'Retirer l’entraînement',
    removeWorkoutConfirm: 'Retirer cet entraînement du programme ?',
    errorRemoveWorkout: 'Échec du retrait de l’entraînement du programme',
    deleteProgramme: 'Supprimer le programme',
    deleteProgrammeConfirm: 'Cette action supprimera le programme définitivement. Continuer ?',
    delete: 'Supprimer',
    errorDeleteProgramme: 'Échec de suppression du programme',
    errorLoadProgramme: 'Échec du chargement du programme',
    programmeNotFound: 'Programme introuvable',
    programmeLabel: 'Programme',
    noObjectiveProvided: 'Aucun objectif indiqué',
    addWorkoutsCTA: 'Ajouter des entraînements',
    backToList: 'Retour à la liste',
    workoutsByWeekDay: 'Entraînements par semaine/jour ({count})',
    noWorkoutsAttached: 'Aucun entraînement rattaché à ce programme',
    weekLabel: 'Semaine {num}',
    noWorkout: 'Aucun entraînement',
    unscheduled: 'Non planifié',
    addWorkoutsTitle: 'Ajouter des entraînements au programme',
    workoutPlaceholder: 'Entraînement {id}',
    weekOrderLabel: 'Semaine (ordre)',
    addAnother: 'Ajouter un autre',
    dayMon: 'Lun',
    dayTue: 'Mar',
    dayWed: 'Mer',
    dayThu: 'Jeu',
    dayFri: 'Ven',
    daySat: 'Sam',
    daySun: 'Dim',
    exercisesCount: '{count} exercices',
    exercisesNotLoaded: 'Exercices non chargés',
    myWorkoutsTitle: 'Mes entraînements',
    myWorkoutsSubtitle: 'Votre liste personnalisée avec des stats rapides',
    searchWorkouts: 'Rechercher des entraînements...',
    workoutsCountFound: '{count} entraînement(s) trouvé(s)',
    programmesBtn: 'Programmes',
    noWorkoutsSearch: 'Aucun entraînement ne correspond à votre recherche',
    noWorkoutsFound: 'Aucun entraînement trouvé',
    clearSearch: 'Effacer la recherche',
    createWorkout: 'Créer un entraînement',
    createAttachExercise: 'Créer & Attacher un exercice',
    workoutTitlePlaceholder: 'Titre *',
    notesPlaceholder: 'Notes',
    durationMinutesPlaceholder: 'Durée (minutes)',
    waterPlaceholder: 'Consommation d’eau (L)',
    newExerciseTitle: 'Nouvel exercice',
    selectedWorkoutId: 'ID entraînement sélectionné : {id}',
    none: 'Aucun',
    exerciseNameLabel: 'Nom de l’exercice *',
    exerciseNamePlaceholder: 'Saisir le nom de l’exercice',
    whereTraining: 'Où vous entraînez-vous ?',
    atHome: 'À la maison',
    locationHelper: 'Choisissez votre salle pour voir ses machines, ou Maison pour tout charger.',
    selectBranch: 'Sélectionner une salle',
    noBranches: 'Aucune salle disponible',
    coachNameSelect: 'Nom du coach (sélection)',
    noCoachesBranch: 'Aucun coach pour cette salle',
    selectBranchFirst: 'Sélectionnez d’abord une salle',
    coachNameManual: 'Nom du coach (manuel)',
    coachNamePlaceholder: 'Entrez le nom du coach ou écrivez le vôtre',
    coachNameHelper: 'La sélection est stockée en texte pour traçabilité.',
    selectMachine: 'Choisir une machine',
    noMachinesLocation: 'Aucune machine pour cet emplacement',
    selectLocationFirst: 'Choisissez où vous vous entraînez pour charger les machines',
    selectMovement: 'Choisir un mouvement',
    selectCharge: 'Choisir une charge',
    setsLabel: 'Séries *',
    repsLabel: 'Répétitions *',
    setsPlaceholder: 'Séries',
    repsPlaceholder: 'Répétitions',
    instructionsLabel: 'Instructions (optionnel)',
    instructionsPlaceholder: 'Saisir des instructions',
    addExercise: 'Ajouter l’exercice',
    errorLoadWorkoutsList: 'Échec du chargement des entraînements. Réessayez.',
    errorLoadBranches: 'Échec du chargement des salles',
    errorLoadMachines: 'Échec du chargement des machines',
    errorLoadCoaches: 'Échec du chargement des coachs pour cette salle',
    errorLoadMovements: 'Échec du chargement des mouvements',
    errorLoadCharges: 'Échec du chargement des charges',
    workoutTitleRequired: 'Le titre de l’entraînement est requis',
    successTitle: 'Succès',
    errorCreateWorkout: 'Impossible de créer l’entraînement',
    selectWorkoutFirst: 'Veuillez sélectionner un entraînement d’abord',
    exerciseFieldsRequired: 'Nom, séries et répétitions sont requis',
    exerciseCreatedAttached: 'Exercice créé et attaché avec succès',
    errorCreateAttachExercise: 'Impossible de créer ou d’attacher l’exercice',
    noOptions: 'Aucune option disponible',
    noNotes: 'Aucune note',
    dateNA: 'Date N/D',
    errorLoadWorkoutDetails: 'Échec du chargement des détails de l’entraînement',
    errorUpdateExerciseData: 'Impossible de mettre à jour les données de l’exercice.',
    errorToggleStatus: 'Impossible de mettre à jour le statut. Réessayez.',
    invalidInput: 'Entrée invalide',
    enterValidOrder: 'Entrez un nombre valide pour l’ordre.',
    orderUpdated: 'Ordre mis à jour !',
    errorUpdateOrder: 'Impossible de mettre à jour l’ordre. Réessayez.',
    confirmDelete: 'Confirmer la suppression',
    confirmDeleteExercise: 'Supprimer cet exercice du workout et le supprimer définitivement ?',
    delete: 'Supprimer',
    exerciseRemoved: 'Exercice supprimé avec succès.',
    errorDeleteExercise: 'Échec de suppression de l’exercice. Réessayez.',
    achNoteCompleted: 'Terminé',
    achNoteNearly: 'Presque terminé',
    achNoteAlmost: 'Quasi fini',
    achNoteGetting: 'En bonne voie',
    achNoteStarted: 'Tout juste commencé',
    achNoteNotStarted: 'Non commencé',
    setsReps: 'Séries x Répétitions',
    achievement: 'Progression',
    achievementRange: 'La progression doit être entre 0 et 100',
    completed: 'Terminé',
    inProgress: 'En cours',
    movement: 'Mouvement',
    machine: 'Machine',
    charge: 'Charge',
    deleteExercise: 'Supprimer l’exercice',
    workoutTitleLabel: 'Entraînement : {title}',
    duration: 'Durée',
    water: 'Eau',
    type: 'Type',
    restDay: 'Jour de repos',
    workoutDay: 'Entraînement',
    done: 'Fait',
    pending: 'En attente',
    noExercisesFound: 'Aucun exercice trouvé.',
    userDefault: 'Utilisateur',
    errorLoadUserData: 'Échec du chargement des données utilisateur',
    sessionExpired: 'Session expirée',
    pleaseLoginAgain: 'Veuillez vous reconnecter',
    errorLoadProgress: 'Échec du chargement des données de progression',
    confirmDeleteProgress: 'Supprimer cette entrée ?',
    deletedTitle: 'Supprimé',
    progressDeleted: 'Entrée supprimée avec succès',
    errorDeleteProgress: 'Échec de suppression de la progression',
    dateRequired: 'La date est requise',
    oneMeasurement: 'Fournissez au moins une mesure',
    dateFormat: 'Entrez la date au format AAAA-MM-JJ',
    validWeight: 'Entrez un poids valide',
    validHeight: 'Entrez une taille valide',
    bodyFatRange: 'Le body fat doit être entre 0 et 100',
    muscleMassRange: 'La masse musculaire doit être entre 0 et 100',
    progressAdded: 'Progression ajoutée avec succès',
    errorSaveProgress: 'Impossible d’enregistrer la progression',
    loadingProgress: 'Chargement des progrès...',
    progressTracker: 'Suivi de progression',
    progressFor: 'Progression de {name}',
    progressSubtitle: 'Suivez poids, masse musculaire et body fat',
    entriesCount: '{count} entrées',
    noEntries: 'Aucune entrée',
    noRecentData: 'Pas de données récentes',
    height: 'Taille',
    muscle: 'Muscle',
    recentTrends: 'Tendances récentes',
    addProgress: 'Ajouter une progression',
    addProgressHint: 'Enregistrez vos mesures pour suivre vos progrès.',
    weightPlaceholder: 'Poids (kg) - optionnel',
    heightPlaceholder: 'Taille (cm) - optionnel',
    bodyFatPlaceholder: 'Body Fat % - optionnel',
    musclePlaceholder: 'Masse musculaire % - optionnel',
    datePlaceholder: 'Date (AAAA-MM-JJ) - requis',
    today: "Aujourd'hui",
    saveProgress: 'Enregistrer la progression',
    history: 'Historique',
    noProgressYet: 'Pas encore de données. Ajoutez une première entrée ci-dessus !',
  },
  ar: {
    authTitle: 'أنس بلس',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    loading: 'جارِ التحميل...',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    passwordHint: '8 أحرف على الأقل مع حرف كبير وصغير ورقم',

    searchPlaceholder: 'ابحث عن القاعات أو المواقع...',
    quickMap: 'الخريطة',
    quickBookings: 'الحجوزات',
    quickWorkouts: 'التمارين',
    activeCount: '{count} نشط',
    locationsTitle: 'فروعنا',
    resultsTitle: 'النتائج',
    nearbyTitle: 'بالقرب منك',
    featuredTitle: 'مميزة',
    viewAll: 'عرض الكل',
    upcomingSessions: 'الحصص القادمة',
    seeAll: 'عرض الكل',
    noLocations: 'لا توجد مواقع',
    adjustSearch: 'جرّب تغيير البحث',
    bookingsModal: 'حجوزاتي',
    upcoming: 'قادم',
    pastSessions: 'حصص سابقة',
    noBookings: 'لا توجد حجوزات',
    startJourney: 'ابدأ رحلتك الرياضية الآن',
    exploreLocations: 'استكشف الفروع',
    allLabel: 'الكل',
    errorTitle: 'خطأ',
    validationTitle: 'تحقق',
    errorLoadProgrammes: 'فشل تحميل البرامج',
    errorLoadWorkouts: 'فشل تحميل التمارين',
    titleRequired: 'العنوان مطلوب',
    userNotIdentified: 'المستخدم غير معروف، يرجى تسجيل الدخول من جديد.',
    errorCreateProgramme: 'فشل إنشاء البرنامج',
    durationWeeksShort: '{count} أسابيع',
    durationNA: 'مدة غير متوفرة',
    noObjective: 'لا يوجد هدف',
    workoutsCount: '{count} تمارين',
    active: 'نشط',
    inactive: 'غير نشط',
    workoutNumber: 'تمرين #{num}',
    orderLabel: 'الترتيب',
    weekDayLabel: 'يوم الأسبوع (1-7)',
    remove: 'حذف',
    myProgrammes: 'برامجي',
    newLabel: 'جديد',
    searchProgrammes: 'ابحث عن البرامج',
    newest: 'الأحدث',
    oldest: 'الأقدم',
    programmesCount: '{count} برنامج',
    reset: 'إعادة ضبط',
    retry: 'إعادة المحاولة',
    noProgrammesFilters: 'لا برامج تطابق عوامل التصفية',
    noProgrammes: 'لا توجد برامج بعد',
    adjustSearchFilters: 'غيّر البحث أو عوامل التصفية',
    createProgrammeHint: 'أنشئ برنامجاً لتنظيم تمارينك',
    clearFilters: 'مسح التصفية',
    createProgramme: 'إنشاء برنامج',
    titleLabel: 'العنوان *',
    programmeTitlePlaceholder: 'عنوان البرنامج',
    objectiveLabel: 'الهدف',
    objectivePlaceholder: 'خسارة وزن، قوة...',
    descriptionLabel: 'الوصف',
    programmeNotesPlaceholder: 'ملاحظات حول هذا البرنامج',
    durationWeeksLabel: 'المدة (أسابيع)',
    durationPlaceholder: 'مثال: 8',
    workoutsInProgramme: 'التمارين في هذا البرنامج',
    addWorkout: 'إضافة تمرين',
    addWorkoutsHelper: 'أضف تمارين لتحديد التسلسل.',
    cancel: 'إلغاء',
    save: 'حفظ',
    accessTitle: 'وصول',
    workoutFallback: 'تعذر تحميل كل تفاصيل التمرين، سيتم عرض المعلومات الأساسية.',
    selectWorkoutPlease: 'يرجى اختيار تمرين واحد على الأقل',
    errorUpdateProgrammeWorkouts: 'فشل تحديث تمارين البرنامج',
    removeWorkoutTitle: 'إزالة التمرين',
    removeWorkoutConfirm: 'إزالة هذا التمرين من البرنامج؟',
    errorRemoveWorkout: 'فشل إزالة التمرين من البرنامج',
    deleteProgramme: 'حذف البرنامج',
    deleteProgrammeConfirm: 'سيتم حذف البرنامج نهائياً. المتابعة؟',
    delete: 'حذف',
    errorDeleteProgramme: 'فشل حذف البرنامج',
    errorLoadProgramme: 'فشل تحميل البرنامج',
    programmeNotFound: 'البرنامج غير موجود',
    programmeLabel: 'برنامج',
    noObjectiveProvided: 'لا يوجد هدف محدد',
    addWorkoutsCTA: 'إضافة تمارين',
    backToList: 'العودة للقائمة',
    workoutsByWeekDay: 'التمارين حسب الأسبوع/اليوم ({count})',
    noWorkoutsAttached: 'لا توجد تمارين مرفقة بهذا البرنامج',
    weekLabel: 'الأسبوع {num}',
    noWorkout: 'لا يوجد تمرين',
    unscheduled: 'غير مجدول',
    addWorkoutsTitle: 'إضافة تمارين للبرنامج',
    workoutPlaceholder: 'تمرين {id}',
    weekOrderLabel: 'الأسبوع (الترتيب)',
    addAnother: 'أضف آخر',
    dayMon: 'اثن',
    dayTue: 'ثلث',
    dayWed: 'أرب',
    dayThu: 'خمس',
    dayFri: 'جمع',
    daySat: 'سبت',
    daySun: 'أحد',
    exercisesCount: '{count} تمارين',
    exercisesNotLoaded: 'التمارين غير محمّلة',
    myWorkoutsTitle: 'تماريني',
    myWorkoutsSubtitle: 'قائمة جلساتك مع إحصاءات سريعة',
    searchWorkouts: 'ابحث عن التمارين...',
    workoutsCountFound: '{count} تمرين',
    programmesBtn: 'البرامج',
    noWorkoutsSearch: 'لا توجد تمارين مطابقة لبحثك',
    noWorkoutsFound: 'لا توجد تمارين',
    clearSearch: 'مسح البحث',
    createWorkout: 'إنشاء تمرين',
    createAttachExercise: 'إنشاء وربط تمرين',
    workoutTitlePlaceholder: 'العنوان *',
    notesPlaceholder: 'ملاحظات',
    durationMinutesPlaceholder: 'المدة (دقائق)',
    waterPlaceholder: 'كمية الماء (لتر)',
    newExerciseTitle: 'تمرين جديد',
    selectedWorkoutId: 'معرف التمرين المحدد: {id}',
    none: 'لا يوجد',
    exerciseNameLabel: 'اسم التمرين *',
    exerciseNamePlaceholder: 'أدخل اسم التمرين',
    whereTraining: 'أين تتدرب؟',
    atHome: 'في المنزل',
    locationHelper: 'اختر القاعة لرؤية أجهزتها، أو المنزل لعرض الجميع.',
    selectBranch: 'اختر القاعة',
    noBranches: 'لا توجد قاعات متاحة',
    coachNameSelect: 'اسم المدرب (اختيار)',
    noCoachesBranch: 'لا مدربين لهذه القاعة',
    selectBranchFirst: 'اختر القاعة أولا',
    coachNameManual: 'اسم المدرب (يدوي)',
    coachNamePlaceholder: 'أدخل اسم المدرب أو اكتب اسمك',
    coachNameHelper: 'يتم حفظ الاختيار كنص لأغراض التتبع.',
    selectMachine: 'اختر الجهاز',
    noMachinesLocation: 'لا أجهزة لهذا الموقع',
    selectLocationFirst: 'اختر مكان التدريب لتحميل الأجهزة',
    selectMovement: 'اختر الحركة',
    selectCharge: 'اختر الوزن',
    setsLabel: 'مجموعات *',
    repsLabel: 'تكرارات *',
    setsPlaceholder: 'المجموعات',
    repsPlaceholder: 'التكرارات',
    instructionsLabel: 'تعليمات (اختياري)',
    instructionsPlaceholder: 'أدخل التعليمات',
    addExercise: 'إضافة تمرين',
    errorLoadWorkoutsList: 'فشل تحميل التمارين، حاول مرة أخرى.',
    errorLoadBranches: 'فشل تحميل الفروع',
    errorLoadMachines: 'فشل تحميل الأجهزة',
    errorLoadCoaches: 'فشل تحميل المدربين لهذا الفرع',
    errorLoadMovements: 'فشل تحميل الحركات',
    errorLoadCharges: 'فشل تحميل الأوزان للجهاز المحدد',
    workoutTitleRequired: 'عنوان التمرين مطلوب',
    successTitle: 'تم بنجاح',
    errorCreateWorkout: 'تعذر إنشاء التمرين',
    selectWorkoutFirst: 'يرجى اختيار تمرين أولا',
    exerciseFieldsRequired: 'الاسم، المجموعات والتكرارات مطلوبة',
    exerciseCreatedAttached: 'تم إنشاء التمرين وربطه بنجاح',
    errorCreateAttachExercise: 'تعذر إنشاء أو ربط التمرين',
    noOptions: 'لا توجد خيارات متاحة',
    noNotes: 'لا ملاحظات',
    dateNA: 'تاريخ غير متوفر',
    errorLoadWorkoutDetails: 'فشل تحميل تفاصيل التمرين',
    errorUpdateExerciseData: 'فشل تحديث بيانات التمرين.',
    errorToggleStatus: 'تعذر تحديث حالة التمرين، حاول مجدداً.',
    invalidInput: 'إدخال غير صالح',
    enterValidOrder: 'أدخل رقماً صالحاً للترتيب.',
    orderUpdated: 'تم تحديث الترتيب!',
    errorUpdateOrder: 'فشل تحديث الترتيب، حاول مجدداً.',
    confirmDelete: 'تأكيد الحذف',
    confirmDeleteExercise: 'إزالة هذا التمرين وحذفه نهائياً؟',
    delete: 'حذف',
    exerciseRemoved: 'تم حذف التمرين بنجاح.',
    errorDeleteExercise: 'فشل حذف التمرين، حاول مجدداً.',
    achNoteCompleted: 'مكتمل',
    achNoteNearly: 'شبه مكتمل',
    achNoteAlmost: 'على وشك الانتهاء',
    achNoteGetting: 'في تقدم',
    achNoteStarted: 'بدأ للتو',
    achNoteNotStarted: 'لم يبدأ',
    setsReps: 'المجموعات × التكرارات',
    achievement: 'الإنجاز',
    achievementRange: 'يجب أن يكون الإنجاز بين 0 و100',
    completed: 'مكتمل',
    inProgress: 'قيد العمل',
    movement: 'الحركة',
    machine: 'الجهاز',
    charge: 'الوزن',
    deleteExercise: 'حذف التمرين',
    workoutTitleLabel: 'التمرين: {title}',
    duration: 'المدة',
    water: 'الماء',
    type: 'النوع',
    restDay: 'يوم راحة',
    workoutDay: 'تمرين',
    done: 'تم',
    pending: 'قيد الانتظار',
    noExercisesFound: 'لا توجد تمارين.',
    userDefault: 'مستخدم',
    errorLoadUserData: 'فشل تحميل بيانات المستخدم',
    sessionExpired: 'انتهت الجلسة',
    pleaseLoginAgain: 'يرجى تسجيل الدخول مرة أخرى',
    errorLoadProgress: 'فشل تحميل بيانات التقدم',
    confirmDeleteProgress: 'هل تريد حذف هذا السجل؟',
    deletedTitle: 'تم الحذف',
    progressDeleted: 'تم حذف سجل التقدم بنجاح',
    errorDeleteProgress: 'فشل حذف سجل التقدم',
    dateRequired: 'التاريخ مطلوب',
    oneMeasurement: 'أدخل مقياساً واحداً على الأقل',
    dateFormat: 'أدخل التاريخ بصيغة YYYY-MM-DD',
    validWeight: 'أدخل وزناً صالحاً',
    validHeight: 'أدخل طولاً صالحاً',
    bodyFatRange: 'نسبة الدهون يجب أن تكون بين 0 و100',
    muscleMassRange: 'نسبة العضلات يجب أن تكون بين 0 و100',
    progressAdded: 'تم إضافة التقدم بنجاح',
    errorSaveProgress: 'تعذر حفظ التقدم',
    loadingProgress: 'جار تحميل التقدم...',
    progressTracker: 'متابعة التقدم',
    progressFor: 'تقدم {name}',
    progressSubtitle: 'تابع الوزن، الكتلة العضلية ونسبة الدهون',
    entriesCount: '{count} إدخالات',
    noEntries: 'لا توجد إدخالات',
    noRecentData: 'لا توجد بيانات حديثة',
    height: 'الطول',
    muscle: 'العضلات',
    recentTrends: 'الاتجاهات الأخيرة',
    addProgress: 'إضافة تقدم جديد',
    addProgressHint: 'احفظ قياساتك لتتبع تقدمك.',
    weightPlaceholder: 'الوزن (كغ) - اختياري',
    heightPlaceholder: 'الطول (سم) - اختياري',
    bodyFatPlaceholder: 'نسبة الدهون % - اختياري',
    musclePlaceholder: 'نسبة العضلات % - اختياري',
    datePlaceholder: 'التاريخ (YYYY-MM-DD) - مطلوب',
    today: 'اليوم',
    saveProgress: 'حفظ التقدم',
    history: 'السجل',
    noProgressYet: 'لا توجد بيانات بعد. أضف أول سجل هنا!',
  },
};

export const defaultLang = 'en';

export const t = (lang, key, vars = {}) => {
  const base =
    translations[lang] && translations[lang][key]
      ? translations[lang][key]
      : translations[defaultLang][key] || key;
  return Object.keys(vars).reduce((acc, k) => acc.replace(`{${k}}`, vars[k]), base);
};

export const supportedLanguages = [
  { code: 'en', label: 'EN' },
  { code: 'fr', label: 'FR' },
  { code: 'ar', label: 'AR' },
];
